config/routes.rb
Rails.application.routes.draw do

	root "welcome#index"

	resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

	validates :description, :link, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@image = Image.all
	end

	def new
		@image = Image.new
	end

	def create
		@image = Image.new(image_params)
		@image.computer = request.ip

		if @image.save
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		@image = Image.find params[:id]
		@image.destroy

		redirect_to root_path
	end

	private
	def image_params
		params.require(:image).permit(:description, :link, :computer);
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@images = Image.all.reverse
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= simple_form_for @image do |image| %>
	
	<div class="mdl-card mdl-shadow--2dp" style="width: 100%;">
		<div class="mdl-card__supporting-text">
			<div class="mdl-grid">
				<div class="mdl-cell mdl-cell--12-col">
					<%= image.input :description %>
					<%= image.input :link %>
				</div>
			</div>
		</div>

		<div class="mdl-card__actions mdl-card--border">
			<%= image.button :submit %>
			<%= link_to "Cancelar", root_path, class: "mdl-button" %>
		</div>
	</div>

<% end %>

app/views/images/new.html.erb
<h1>Nova imagem</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width= device-width, initial-scale=1, ">
    <title>Teste</title>
    <%= csrf_meta_tags %>

    <!-- MDL -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
		<script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 	 'sweetalert' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="mdl-layout mdl-layout--fixed-header">
  		<header class="mdl-layout__header">
  			<div class="mdl-layout__header-row">
          <%= link_to "Imaginando", root_path, class: "mdl-title" %>
  				<div class="mdl-layout-spacer"></div>

  				<nav class="mdl-navigation">
            <%= link_to "add_circle", new_image_path, class: "mdl-navigation__link material-icons" %>
  				</nav>
  			</div>
  		</header>

	  	<main class="mdl-layout__content">
	  		<div class="mdl-grid">
	       	<div class="mdl-cell mdl-cell--1-col mdl-layout--medium-screen-only"></div>
	        <div class="mdl-cell mdl-cell--10-col mdl-cell--8-col-tablet">
	          <%= yield %>
	        </div>
	    	</div>
	  	</main>

    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello World</h1>

<div class="mdl-grid">
	<% @images.each do |image| %>	
		<div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp">

			<div class="mdl-card__supporting-text">
				<%= image_tag image.link, class: "image" %>	
			</div>
			
			<div class="mdl-card__actions mdl-card--border">	
				<%= image.description %>
				<% if image.computer == request.ip %>
					<div class="mdl-layout-spacer"></div>
  				<%= link_to "delete", image_path(image.id), class: "material-icons showConfirm", data: { confirm: "Apagar imagem", text: "Realmente desejar apagar está imagem?"}, method: :delete %>
				<% end %>
			</div>
			
		</div>
	<% end %>
</div>